### ISSUE TITLE
LB Mod Installer: Enhancements request

### ISSUE THREAD

**Issue by StardustZfighter** [LazyBone152/XV2-Tools#15]
1. Function Support for "Values". Example: PartSet value="" in CUS. (Great for editing CUS data for awoken skills)
2. Value or ID skip. Basically making installer not change some data that is specified by us. Example: specifying PUP ID="" and CUS_Aura value="" in CUS to not change during LB mod installation. (Great for leaving some data as they were when installed by eternity's installer)
3. BAC and BCS Subentry append installation. basically enabling subentries for these files to be added without replacing the whole entry. Example: adding a <sound> subentry to BAC entry without having that whole entry in bac.xml just that one subentry. Same for BCS subentries. (Great for adding skill upgrades to vanilla awoken skills with different mods while avoiding compatibility issues between those mods)

**Comment by LazyBone152** [comment]
1. Future versions will support bindings for everything, so this should work
2. A great idea, but I'm not sure if it can be added. I will think on this more.
3. This could be done for BCS (the user would need to specify if they are installing a part, rather than a whole PartSet). For BAC it can't be done in a good way so I wont add it there.

**Comment by LazyBone152** [comment]
So after a bit of thinking I may have a way to do 2 in a generic way that works anywhere, but due to its hacky nature it will be an opt in feature (probably a value on the File entry, like SkipBindingEnabled=”true”).

**Comment by LazyBone152** [comment]
1 and 2 will be in 3.9.
