### ISSUE TITLE
EMD Corruption

### ISSUE THREAD

**Issue by LOLDJ23** [LazyBone152/XV2-Tools#19]
Hi Lazybone, i'm reporting this issue where seems that your tool corrupts the EMDs of all the SSJ4 characters in the game, i'm talking about Rists and Face base, no errors with other characters's rists or face and no errors about other EMDs of SSJ4 characters.
https://ibb.co/cgr31t0 here the link to the image for the error.

**Comment by LazyBone152** [comment]
I'm aware of this bug but have been unable to find the exact cause. 

EMDs were never actually supposed to be serializable - I just quickly wrote a parser for it ages ago for another project and it eventually made its way into the serializer. SO interest in fixing it was low, especially since there's other tools for EMD.

**Comment by LazyBone152** [comment]
Should now be fixed in 2.9.
