### ISSUE TITLE
An error on xenokit

### ISSUE THREAD

**Issue by Evt1412** [LazyBone152/XV2-Tools#75]
hi,
i got an issue by open the tool Xenokit, so after i installed it appear always this error and even by using charcter or skills. How can i solve this error ?

![image](https://github.com/LazyBone152/XV2-Tools/assets/98337277/da5d2475-e3e6-4db3-b334-5e0b417fcc99)

**Comment by LazyBone152** [comment]
When you go into the settings (File -> Settings on the top menu), and go over to the Game Directory tab, is the game dir set? From the screenshot you posted its clear that XenoKit is unable to load anything, otherwise you would at least have 1 item in the outliner already.

If its not set, then you will need to browse to the DB Xenoverse folder and then reset the tool. Then it should work.

If the path is set, then post the full error message (copy it with the blue button) and I can take a deeper look at the issue.

**Comment by Evt1412** [comment]
first of all, thanke you for your quick reply and second i was able to fix that error. I read somewhere on your side i have to put a xv2 tool folder into the xenokit folder and it works... So thank you anyway

**Comment by Rellagram** [comment]
i tried that but nothing work
